### ISSUE TITLE
Make it possible to use different types of Smart Edges at the same time

### ISSUE THREAD

**Issue by Ishtiaq-Ahmad** [tisoap/react-flow-smart-edge#11]
Hello dear,
This is pretty awesome feature that you have developed. lots of appreciation for this. i have been using this nice feature with React flow. during the development I got a weird problem. SmartEdgeProvider wrap React flow, whenever i change the SmartEdgeProvider  options then smart edge applies for all edges. and this is not fulfilling my requirement. could you tell me please is it possible to control smart edge individually or if this feature is not available could you add this feature please? you can see a video below where i have highlighted smart edges with green color.

https://user-images.githubusercontent.com/67997286/152481444-4dcdf294-d368-4a3e-8c0e-f0978a3d06a8.mp4

**Comment by tisoap** [comment]
Hi @Ishtiaq-Ahmad ! Currently it is not possible to control options for individual smart edges, the options are global for all

**Comment by tisoap** [comment]
Hey @Ishtiaq-Ahmad , I've released a beta version that makes it possible to configure multiple different smart edge components to be used at the same time, could you try it?

Available to test using the `beta` tag:
```
npm install @tisoap/react-flow-smart-edge@beta
```

New documentation can be found [here](https://github.com/tisoap/react-flow-smart-edge/tree/feat/factory-function#readme)
