### ISSUE TITLE
Allow developers to change the path finding function

### ISSUE THREAD

**Issue by lichenglu** [tisoap/react-flow-smart-edge#14]
First of all, thanks for the great package! It saves me tons of time. 

Originally, the package did not seem to be "smart" on my end (still using the `BezierEdge` from `react-flow`). I then found out that the length of `smoothedPath` for me is always smaller or equal to 2, which fallbacks to the edges of `react-flow` (see [codes here](https://github.com/tisoap/react-flow-smart-edge/blob/15a759f5ed423888c12037fc772c694373cf958c/src/SmartEdge/index.tsx#L86)). Then I was thinking it cannot be that `smoothedPath` is always that case. It turns out there is a bug in the dependency `pathfinding`, where no coordinate will be recorded if coming across a block (start and end coordinate will not be updated either).

```javascript
function smoothenPath(grid, path) {
        ....
        blocked = false;
        ....
        if (blocked) {
            lastValidCoord = path[i - 1]; // THIS IS NOT DEFINED AND CAUSE AN INTERNAL ERROR
            newPath.push(lastValidCoord);
            sx = lastValidCoord[0];
            sy = lastValidCoord[1];
        }
    }
    
    newPath.push([x1, y1]);

    return newPath;
}
```

The fix is easy but it seems that no one is maintaining `pathfinding` anymore (e.g., https://github.com/qiao/PathFinding.js/pull/192).

## Suggestions
1. Maybe `react-flow-smart-edge` should use a fork of `pathfinding` to have known bugs fixed?
2. Even better, maybe we can find a more up-to-date package related to graph theory as this might be maintainable in the long run?

**Comment by tisoap** [comment]
Hey @lichenglu thanks for pointing it out! When I choose `pathfinding` as a dependency I didn't care that it wasn't being maintained anymore, since "path finding" is a solved problem, but turns out there's still bugs in it.

I don't feel confident in forking/maintaining it, which leaves the option to find another up to date dependency

**Comment by lichenglu** [comment]
>

**Comment by tisoap** [comment]
Thinking on how to circumvent this without putting the burden on me to update/change the path finding dependency, I'm planning to create a factory function. Developers can "build" their own versions of a smart edge passing down configurations to this factory function, and I'll expose the option to change the default path finding function.

**Comment by tisoap** [comment]
Hey @lichenglu !  I've released a beta version that makes it possible to configure the path finding function using a `smartEdgeFactory`, could you test if it can be used to solve your use case?

Available to test using the `beta` tag:
```
npm install @tisoap/react-flow-smart-edge@beta
```

New documentation can be found [here](https://github.com/tisoap/react-flow-smart-edge/tree/feat/factory-function#readme)
