### ISSUE TITLE
Timeline of suport for v10 of react-flow-renderer

### ISSUE THREAD

**Issue by azuruce** [tisoap/react-flow-smart-edge#15]
Hi, this repo is awesome. I wonder when we can expect support for v10 of react-flow-renderer. Specifically, how do we plan to support new group feature.

For v10 details, here is a link https://github.com/wbkd/react-flow/pull/1555

**Comment by leejustin** [comment]
The issue you referenced has already been closed. v10 has been released.

**Comment by azuruce** [comment]
Hi, I mean ract-flow-smart-edge does not workt with react-flow-render v10 due to the breaking change in v10. Is v10 support planned and what's the timeline?

**Comment by leejustin** [comment]
Sorry I misunderstood the context of your issue. My apologies.

**Comment by AnhHuy02** [comment]
@leejustin 
He means Smart Edge currently supports React Flow v9.
He wants the author to migrate this library to support React Flow v10,

**Comment by tisoap** [comment]
Hey, author here! I do plan to migrate to v10 of `react-flow-renderer`. The timeline is "when it's ready"

**Comment by tisoap** [comment]
Good news everyone! Version `0.5.0` is now compatible with React Flow v10, didn't take as long as I thought it would be
