### ISSUE TITLE
How to integrate it with existing custom edge?

### ISSUE THREAD

**Issue by kaushalendra-pandey** [tisoap/react-flow-smart-edge#16]
Hi. I have multiple types of edges in my setup. I want to make each one of them smart. From the docs, if we give the type as SmartEdge, it doesn't intersect. How can I make my custom edge inherit these properties and on top of them use properties which are unique to them?

**Comment by tisoap** [comment]
Hey @kaushalendra-pandey ! This package includes custom Edges that themselves do path finding. It's not a package to transform other edge types into "smart" ones. If you want a different type of edge that it's not available on this package to do path finding, you'll need to implement it on your own.
