### ISSUE TITLE
Describe supported React Flow versions on README

### ISSUE THREAD

**Issue by abhishekopsteq** [tisoap/react-flow-smart-edge#20]
![image](https://user-images.githubusercontent.com/95271692/164674309-ca3b2e36-a29b-4e6a-b133-bb01b9702076.png)

while working on current version v1.0.0 facing the above issue but  I used version 0.4.0 its worked well now I need to implement SmartStepEdge using version v1.0.0
Need guidance. 
Thanks in advance

**Comment by tisoap** [comment]
Hey @abhishekopsteq ! You need to update your react-flow-renderer to version 10, I've dropped support for version 9 and bellow

**Comment by tisoap** [comment]
Fixed on version `1.0.1`
