### ISSUE TITLE
How to increase the height of SmartStepEdge?

### ISSUE THREAD

**Issue by abhishekopsteq** [tisoap/react-flow-smart-edge#22]
![image](https://user-images.githubusercontent.com/95271692/165095943-07ba577c-0d73-4360-8620-87ac875e7d08.png)

Hello @tisoap,

How can I increase the height of SmartStepEdge of Source Point while taking a turn
Please give me suggestions
Thanks

**Comment by tisoap** [comment]
Hey @abhishekopsteq ! One thing you can do is to use the exported `stepEdgeFactory` function to create a customized SmartStepEdge with a bigger value for `nodePadding`, so the edge will avoid more the borders of a node, check the documentation for that

**Comment by tisoap** [comment]
There hasn't been a follow up, so I'll assume my suggestion was enough
