### ISSUE TITLE
Provide support for custom Edge labels

### ISSUE THREAD

**Issue by NithishG** [tisoap/react-flow-smart-edge#23]
First of all thank you @tisoap for this amazing library.

We have a requirement of displaying a button along with the edge label, through which we want to perform some actions. Something similar to what we have as `CustomEdge` in react-flow.

Below is the screenshot of what we are actually trying to achieve

<img width="905" alt="Screenshot 2022-04-26 at 1 04 31 PM" src="https://user-images.githubusercontent.com/41664135/165246852-3f258035-db6b-413e-b409-4c5c891922b2.png">

**Comment by tisoap** [comment]
Hey @NithishG , I'm glad you liked the library!

I see, you guys need to be able to implement an edge with an button, like [this example on React Flow docs](https://reactflow.dev/docs/examples/edge-with-button/). Currently the smart edges in this package only allow for text labels using the [edge options](https://reactflow.dev/docs/api/edges/edge-options/), but I can see this being a nice addition.

**Comment by atruttmann** [comment]
This library looks awesome! I have the same use case - a custom edge with a button - and would love to see support for this too. I would like to center the button the same way as React Flow provides with `getBezierEdgeCenter`.

**Comment by tisoap** [comment]
@atruttmann  I'm working on this, it's a bit harder since I have to re-structure the library around a `getSmartEdge` function instead of factories, so it'll be a breaking change. The good thing is it will have a very similar API to React Flow's examples, and it'll give more control to developers when the path-finding happens

**Comment by tisoap** [comment]
Hey @NithishG and @atruttmann ! I've released a [beta version of the library](https://github.com/tisoap/react-flow-smart-edge/pull/30) that exposes a `getSmartEdge` function, that allows for custom edges with custom labels to be created, could you guys test it out?

Available to test using the `beta` tag. Install with NPM:
```
npm install @tisoap/react-flow-smart-edge@beta
```

New documentation can be found [here](https://github.com/tisoap/react-flow-smart-edge/tree/feat/custom-labels-support#readme).

**Comment by atruttmann** [comment]
Hey @tisoap, these updates are fabulous! 🥳 This was really easy to add to my project and works really well for my use case. From my testing so far it all works great, I'll let you know if anything changes.

**Comment by NithishG** [comment]
Hey @tisoap, thanks for the update, it looks great and working as expected in order to provide a custom label. 

But one thing that I felt is that how can I chose what kind of smart edge I need using `getSmartEdge`?

We have extra info about the type of edge as part of `data` through which we used to identify what kind of smart edge need to be drawn and this is how the previous implementation looks like

This is my `CustomEdge` component

```jsx
const CustomEdge = props => {
  const { data: { edgeLineType } } = props;
  const edgeProps = { ...props, style: { strokeWidth: 2.2 }, labelStyle: { fontSize: '12px' } };
  switch (edgeLineType) {
    case 'straight': {
      return <SmartStraightEdge { ...edgeProps } />;
    }
    case 'step': {
      return <SmartStepEdge { ...edgeProps } />;
    }
    default: {
      return <SmartBezierEdge { ...edgeProps } />;
    }
  }
};
```

In the other component where we render `ReactFlow`

```jsx
const edgeTypes = {
  customEdge: CustomEdge,
};

// Rest of the code
     <ReactFlow
            edgeTypes={ edgeTypes }
            // other props
     />
```

Any suggestions how I can achieve this?

**Comment by tisoap** [comment]
@NithishG 

> how can I chose what kind of smart edge I need using getSmartEdge?

You would need pass an `options` object to the `getSmartEdge`, with the specific `drawEdge` and `generatePath` functions to create the desired shape and behavior, you can see some examples on the [Advanced Custom Smart Edges](https://github.com/tisoap/react-flow-smart-edge/tree/feat/custom-labels-support#advanced-custom-smart-edges) sections of the README.

To create a custom edge that behaves the same way as the built-in `SmartStepEdge` for example, you would need to do something like this:

```jsx
import {
	getSmartEdge,
	svgDrawStraightLinePath,
	pathfindingJumpPointNoDiagonal
} from '@tisoap/react-flow-smart-edge'

// ...

const result = getSmartEdge({
	sourcePosition,
	targetPosition,
	sourceX,
	sourceY,
	targetX,
	targetY,
	nodes,
	options: {
		drawEdge: svgDrawStraightLinePath,
		generatePath: pathfindingJumpPointNoDiagonal,
	}
})
```
Now I realize the README needs better examples, and of the importance of working on issue #29

**Comment by NithishG** [comment]
Hey @tisoap Thank you very much for the quick reply 🙌🏼. This works like a charm 🥳 🎉 as per our need. Will be waiting for the official release of this version of the library.

And sorry for missing out to check some of the examples under README as I was checking the source code and found that the `getSmartEdge` also accepts `options` as well. But, haven't checked that the methods under `functions` like `svgDrawStraightLinePath`, `pathfindingJumpPointNoDiagonal` were also exposed to outside world.

I would be happy to help to work on #29

**Comment by tisoap** [comment]
@NithishG @atruttmann : Version `2.0.0` was published
