### ISSUE TITLE
Equivalent to getBezierPath or getSimpleBezierPath

### ISSUE THREAD

**Issue by shemeshx** [tisoap/react-flow-smart-edge#26]
Hey,
First of all, thanks for this library!!!! it is huge help for me :).

I'm looking for equivalent for getBezierPath/getSimpleBezierPath hooks of react-flow-renderer when creating custom edges.
https://reactflow.dev/docs/examples/edges/

there is a way to implement the smart edge functionality in this case?

thanks!!!

**Comment by tisoap** [comment]
Hey @shemeshx ! This package does have some more [advanced configuration](https://github.com/tisoap/react-flow-smart-edge#advanced-smart-edge-configuration) using the `smartEdgeFactory` function, that let's you customize how an Smart Edge behaves. It this what you're looking for?

**Comment by tisoap** [comment]
There hasn't been a follow up, so I'll assume my suggestion was enough
