### ISSUE TITLE
Option to pass only specific nodes that edges should dodge

### ISSUE THREAD

**Issue by sushantgulati1** [tisoap/react-flow-smart-edge#28]
Hey @tisoap,

Is there a way/hack to make the edges dodge only some specific nodes instead of all nodes?
If not, It'll be nice if we could pass node IDs or a filter function in the _factory_ functions.

**Comment by tisoap** [comment]
Hey @sushantgulati1 ! Currently there is not, this library always uses all nodes for pathfinding, using React Flow's [`useNodes` hook](https://reactflow.dev/docs/api/hooks/use-nodes/) behind the scenes. I'll add this one to the backlog.

Now I'm curious, what's your use case?

**Comment by sushantgulati1** [comment]
Thanks, @tisoap!

When I'm showing the edges I want to highlight some specific nodes (actually more like not highlighting a set of nodes), and I don't really need the pathfinding algorithm to consider the other ones as they are kind of in the backdrop.

**Comment by tisoap** [comment]
Hey @sushantgulati1 ! I've released a [beta version of the library](https://github.com/tisoap/react-flow-smart-edge/pull/30) that exposes a `getSmartEdge` function, that allows for custom edges with custom labels to be created. This function takes a `nodes` argument, so you can use `useNodes` from React Flow but filter the results to your liking before running the function, could you test it out?

Available to test using the `beta` tag. Install with NPM:
```
npm install @tisoap/react-flow-smart-edge@beta
```

New documentation can be found [here](https://github.com/tisoap/react-flow-smart-edge/tree/feat/custom-labels-support#readme).

**Comment by sushantgulati1** [comment]
Thanks, @tisoap 🙏

Works like a charm.

**Comment by tisoap** [comment]
@sushantgulati1 Version `2.0.0` was published
