### ISSUE TITLE
Update to be compatible with React Flow 11

### ISSUE THREAD

**Issue by antipasvasil** [tisoap/react-flow-smart-edge#39]
It was mentioned: "This package is only compatible with [version 10 or newer of React Flow Edge](https://reactflow.dev/docs/guides/migrate-to-v10/)." 

- Actualy it is not compatable with v.11 of it. [(here)](https://reactflow.dev/docs/guides/migrate-to-v11/)
- we migrated to v.11 of react-flow and when we started our project we had and still having an error:
![Screenshot 2022-10-10 140639](https://user-images.githubusercontent.com/12182899/194853767-aa5c84f3-6834-4557-9f73-f9ad31517f41.png)

The library **react-flow-smart-edge** looking for old dependency of react-flow : "**react-flow-renderer**" but it should be **reactflow**

So, what can be done about it?

**Comment by tisoap** [comment]
Hey @antipasvasil , thanks for letting me know! I'll need to update the edge to use the new imports from ReactFlow 11, and this should be a breaking change

**Comment by antipasvasil** [comment]
@tisoap , thank you so mutch for you answer. I will look forward to update it.

**Comment by tisoap** [comment]
@antipasvasil v3 with React Flow v11 support released under beta:

```bash
npm install @tisoap/react-flow-smart-edge@beta
```

**Comment by antipasvasil** [comment]
@tisoap thank you, i will.

**Comment by tisoap** [comment]
[v3 of Smart Edge with React Flow v11 support released](https://github.com/tisoap/react-flow-smart-edge/releases/tag/v3.0.0)
