### ISSUE TITLE
In version 3.0 Beta - Edge between 2 nodes goes away if the nodes are close to each other

### ISSUE THREAD

**Issue by DraksBG** [tisoap/react-flow-smart-edge#41]
Me and @antipasvasil are collogues and are working on the Beta version. There is a problem when 2 nodes are close to each other - the edge between them goes to a fixed location(at (0, 0) coordinates. 

**To Reproduce**
1. Go to any nodes that have connection (Edge) between them
2. Start dragging one of the node towards the other node that is connected
4. As they get closer the connection (Edge) has been transferred to 0,0 coordinates 

**Expected behavior**
No matter how close any nodes that are connected are getting close the connection should remain between them and not disappear 

**Screenshots**

**Desktop (please complete the following information):**
OS: Windows 10, 11
Browser Chrome, Firefox
![screen_1](https://user-images.githubusercontent.com/52380770/199676615-1d075841-f2c5-4a1e-aeef-3556ab0c348b.png)
![Screen_2](https://user-images.githubusercontent.com/52380770/199676611-47f9ff47-9654-41c7-b6cf-019f80000be5.png)

**Comment by antipasvasil** [comment]
@tisoap i would like one again to thank you of the quick response regarding updaiting vesrion. Exactly as my collogues @DraksBG mentiopned on the top, there is a problem when 2 nodes are close to each other. We know how to mask it but it is not good aproache. I will really apriciate if you can help us to handle that situation. Thank you in advance.

**Comment by tisoap** [comment]
Hey guys! Could you please provide a minimal working example on [CodeSandbox](https://codesandbox.io/)? I won't tackle issues where the problem can't be reproduced
