### ISSUE TITLE
Props that are generated  when you start dragging new connection are missing for <StepEdge /> in react flow v11

### ISSUE THREAD

**Issue by DraksBG** [tisoap/react-flow-smart-edge#42]
On previous version of ReactFlow v10 whenever you start dragging new connection (Edge) to connect towards a new node the props that were coming and that were needed for <SmartEdge /> were sourceX sourceY and  targetX targetY everything was working as it should be, while as after updating to ReactFlow v11 and SmartEdge v3.0 when you start to create a connection the line is disappearing and you can't see it until you connect it, and the props that are specified are missing you got an error as well because of that.

**Minimal Example**
 Share an URL with a minimal example on [CodeSandbox](https://codesandbox.io/) or a minimal GitHub repository where the error happens. **Reported bugs without this link will not be worked on!**

**To Reproduce**
1. Update to ReactFlow v11 
2. Select and Edge and start dragging new connection
3. The connection is not visible 
4. Until you connect it to the new node and props are missing 

**Expected behavior**
The connection should be visible from the begging of the dragging and props shouldn't be missing

**Actual behavior**
The connection is disappearing and the props are missing 

**Desktop (please complete the following information):**
 - OS: [Windows 10-11]
 - Browser [chrome, firefox]
 - Version [latest]
 
**Screenshots and Videos**

React flow v10  SmartEdge v2.0.0
![React_flow_v10](https://user-images.githubusercontent.com/52380770/199692255-f09fad96-779b-4293-993d-416f281176d4.png)
https://user-images.githubusercontent.com/52380770/199692811-140fe4b3-1109-406f-88e1-b3ecb8e4cc76.mp4

React flow v11 SmartEdge v3.0.0 beta
![React_flow_v11](https://user-images.githubusercontent.com/52380770/199693378-79d0a273-5d11-473f-8eed-61a778f9d8fd.png)
https://user-images.githubusercontent.com/52380770/199693387-30f6b75e-ab72-4b0a-8083-ab9b64134d8e.mp4

**Comment by tisoap** [comment]
Hey @DraksBG ! Could you please provide a minimal working example on [CodeSandbox](https://codesandbox.io/)? I won't tackle issues where the problem can't be reproduced

**Comment by tisoap** [comment]
Closed due to lack of a minimal reproducible example
