### ISSUE TITLE
Make edges not overlap each other

### ISSUE THREAD

**Issue by albohlabs** [tisoap/react-flow-smart-edge#43]
### Is your feature request related to a problem? Please describe.

There are multiple nodes layouted^TM by elkjs and afterwards painted on the canvas. The nodes are not draggable, so the user can change the position and trigger the recalculation of the edges by PathFinding.js.
The Problem here is, that the user is not able to recognize which edge connects which nodes. 

### Describe the solution you'd like

I thought that marking the edge path points via `setWalkableAt` as not walkable would force the edges to not overlay each other anymore. What do you think about this?

### Describe alternatives you've considered

Hacking on the PathFinding.js implementation.

### Additional context

![image](https://user-images.githubusercontent.com/163665/201657155-acedc5c9-6060-4c89-835c-e20142c88831.png)

**Comment by tisoap** [comment]
Hey @albohlabs ! Making edges not overlap with each other is outside the scope of this package, and trying to do so it's actually impossible depending on the number of nodes and edges. It's the same as trying to solve the [three utilities problem](https://en.wikipedia.org/wiki/Three_utilities_problem).
