### ISSUE TITLE
Connection line appears broken when using specific grid snapping 

### ISSUE THREAD

**Issue by DraksBG** [tisoap/react-flow-smart-edge#44]
### Is your feature request related to a problem? Please describe.

Hello @tisoap we are having the following situation when using SmartEdge with GridSnapping 

we are having custome grid snaping position and when we connect a parent node to three child nodes at some point the connection gets broken and it's not always a straight line.

My question is, is there a way always to be sure to make the connection straight when using StepEdge, can you suggest a fix if you have ever come across such a problem.

The code for what we use is as follows for the gird snapping and smartEdge:

`export const snapGridValue: SnapGridValueProps = {
    snapGrid: [90, 60],
    snapToGrid: true,
    backgroundGap: [90, 60],
    sizeCrossDots: 40,
    backgroundGridColor: '#e1e1e1',
}`

`  const getSmartEdgeResponse = getSmartEdge({
        sourcePosition,
        targetPosition,
        sourceX,
        sourceY,
        targetX,
        targetY,
        nodes: updatedNodes,
        options: {
            drawEdge: svgDrawStraightLinePath,
            generatePath: pathfindingJumpPointNoDiagonal,
        },
    })`

### Describe the solution you'd like

We have been thinking that we might need to create a custom function for svgDrawStraightLinePath if there is no other way.

### Describe alternatives you've considered

Other way is to have a custom implementation for a position algorithm because in order for the nodes to always stayed at some position that will not allow for the connections to become broken, but there is a lot of different cases and there always might be some discrepancies 

### Additional context

Here is an image of the issue that we are tying to solve.

![image-2022-12-01-08-52-49-896](https://user-images.githubusercontent.com/52380770/207274320-afd8d6d1-17b4-41d8-856c-f753ddb8dc56.jpg)

**Comment by tisoap** [comment]
Hey @DraksBG ! What You're describing seems to be an bug, could you please create a new issue but using the "Bug report" option instead? Thanks!

![Screenshot 2022-12-13 at 12 35 15](https://user-images.githubusercontent.com/28565117/207376709-cddaa94d-4d10-4af6-8c0e-ac63d671948f.png)

**Comment by tisoap** [comment]
Reopened as a bug:
https://github.com/tisoap/react-flow-smart-edge/issues/45
