### ISSUE TITLE
Demo page/Storybook is no longer working

### ISSUE THREAD

**Issue by jp-domino** [tisoap/react-flow-smart-edge#46]
### Describe the Bug

Getting a 404 at https://tisoap.github.io/react-flow-smart-edge/

<img width="798" alt="image" src="https://user-images.githubusercontent.com/102775996/216692245-c97d4d24-5c55-47a5-8b3a-bf76486c4c4f.png">

### Minimal Example

https://tisoap.github.io/react-flow-smart-edge/

### Steps to Reproduce the Bug or Issue

Go to https://tisoap.github.io/react-flow-smart-edge/

### Expected behavior

Expected Storybook

### Platform

macOS + Chrome

**Comment by tisoap** [comment]
Thanks for pointing that out @jp-domino ! I'll look into this when I have the time

**Comment by tisoap** [comment]
Demo page is online again
