### ISSUE TITLE
Edge labels getting overlapped

### ISSUE THREAD

**Issue by NithishG** [tisoap/react-flow-smart-edge#50]
### Describe the Bug

We have used this library in our application for connecting two edges. Theres's an issue that we have noticed that the edge labels are getting overlapped one over the other as we have lot of nodes connecting each other. 

### Minimal Example

https://codesandbox.io/s/edge-overlapping-32omg0?file=/src/Flow.js

### Steps to Reproduce the Bug or Issue

Go to the code sandbox, we can see the edge labels getting overlapped on each other.

### Expected behavior

As a user, we would like the edges not getting overlapped and should be drawn in such a way that both the labels should be displayed properly. 

Is there any way we can achieve this by providing or customising the props, that also would be much helpful for us.

### Screenshots or Videos

<img width="697" alt="image" src="https://github.com/tisoap/react-flow-smart-edge/assets/41664135/1fad7f57-767a-43dc-afb4-5e3cee2bb674">

### Platform

- OS: macOS, Windows, Linux
- Browser: Chrome, Safari, Firefox

**Comment by tisoap** [comment]
Hey @NithishG ! This isn't an issue that's exclusive to `react-flow-smart-edge`, this would happen with any edge by default. As proof, I've edited your example to use React Flow's `StepEdge` instead and was also able to reproduce overlapping labels:
https://codesandbox.io/s/edge-overlapping-counter-example-lbfiq2?file=/src/Flow.js

![image](https://github.com/tisoap/react-flow-smart-edge/assets/28565117/a7cafa54-a17b-4d0b-9f9c-21cdc870650a)

The built-in smart edges by default will render labels as text roughly in the middle of the drawn line. If you want more control over when, where and how they are rendered, you'll need to use the `getSmartEdge` custom hook and build your own edge component. There's the [smart edge with button example](https://github.com/tisoap/react-flow-smart-edge/tree/main#example-1) from this repo, and the [Edge Label Renderer example](https://reactflow.dev/docs/examples/edges/edge-label-renderer/) from React Flow that should help you get started.

**Comment by tisoap** [comment]
This issue is related to this feature request: https://github.com/tisoap/react-flow-smart-edge/issues/25
