### ISSUE TITLE
squared off edges

### ISSUE THREAD

**Issue by usama-pc** [tisoap/react-flow-smart-edge#8]
Nice work!

I was wondering if there was a way to make the edges squared off instead of the non-uniform curves that it currently draws.

**Comment by usama-pc** [comment]
Should do with the following block in `generatePath.ts` I guess?

```
 const finder = new AStarFinder({
    diagonalMovement: DiagonalMovement.Always,
    allowDiagonal: true,
    dontCrossCorners: true,
  });
```

**Comment by tisoap** [comment]
Hey @usama-pc ! The non-uniform curves are actually implemented by `drawSmoothLinePath` on `src/SmartEdge/drawSvgPath.ts`. I do have a `drawStraightLinePath` implementation but I haven't exposed it yet

**Comment by tisoap** [comment]
@usama-pc Version 0.4.0 now exposes [more options](https://github.com/tisoap/react-flow-smart-edge#options) which allows more control over the line shape.
